export const products = [
	{
		id: 'rec43w3ipXvP28vog',
		title: 'high-back bench',
		company: 'ikea',
		image: 'https://picsum.photos/1080/720/?random=1',
		price: 9.99,
	},
	{
		id: 'rec4f2RIftFCb7aHh',
		title: 'albany table',
		company: 'marcos',
		image: 'https://picsum.photos/1080/720/?random=2',
		price: 79.99,
	},
	{
		id: 'rec8kkCmSiMkbkiko',
		title: 'accent chair',
		company: 'caressa',
		image: 'https://picsum.photos/1080/720/?random=3',
		price: 25.99,
	},
	{
		id: 'recBohCqQsot4Q4II',
		title: 'wooden table',
		company: 'caressa',
		image: 'https://picsum.photos/1080/720/?random=4',
		price: 45.99,
	},
	{
		id: 'recDG1JRZnbpRHpoy',
		title: 'dining table',
		company: 'caressa',
		image: 'https://picsum.photos/1080/720/?random=5',
		price: 6.99,
	},
	{
		id: 'recNWGyP7kjFhSqw3',
		title: 'sofa set',
		company: 'liddy',
		image: 'https://picsum.photos/1080/720/?random=6',
		price: 69.99,
	},
	{
		id: 'recZEougL5bbY4AEx',
		title: 'modern bookshelf',
		company: 'marcos',
		image: 'https://picsum.photos/1080/720/?random=7',
		price: 8.99,
	},
	{
		id: 'recjMK1jgTb2ld7sv',
		title: 'emperor bed',
		company: 'liddy',
		image: 'https://picsum.photos/1080/720/?random=8',
		price: 21.99,
	},
	{
		id: 'recmg2a1ctaEJNZhu',
		title: 'utopia sofa',
		company: 'marcos',
		image: 'https://picsum.photos/1080/720/?random=9',
		price: 39.95,
	},
	{
		id: 'recvKMNR3YFw0bEt3',
		title: 'entertainment center',
		company: 'liddy',
		image: 'https://picsum.photos/1080/720/?random=10',
		price: 29.98,
	},
	{
		id: 'recxaXFy5IW539sgM',
		title: 'albany sectional',
		company: 'ikea',
		image: 'https://picsum.photos/1080/720/?random=11',
		price: 10.99,
	},
	{
		id: 'recyqtRglGNGtO4Q5',
		title: 'leather sofa',
		company: 'liddy',
		image: 'https://picsum.photos/1080/720/?random=12',
		price: 9.99,
	},
];
